### ISSUE TITLE
Index redirect doesn't work

### ISSUE THREAD

**Issue by mjablecnik** [tipsy/javalin-auth-example#1]
When I try adress without path, for example: `http://localhost:4567/`
It should me redirect to `http://localhost:4567/users` path when I see this in code:
```
    app.routes {
        get("/") { ctx -> ctx.redirect("/users") }
        path("users") {
```
 but this don't work and show me only text: `Unauthorized`

When I go directly to `http://localhost:4567/users` -> it works right.

**Comment by tipsy** [comment]
Yeah, that's me forgetting to add a role to the `get`. It should be 

```
get("/", { ctx -> ctx.redirect("/users") }, ROLE)
```
